[package]
name = "async-oneshot"
version = "0.1.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ping-pong-cell = { git = "https://github.com/irrustible/ping-pong-cell", branch = "main" }